### ISSUE TITLE
debuging purpose where to see the deployment logs

### ISSUE THREAD

**Issue by Hanati** [ideonate/cdsdashboards#2]
I tried the "The Littlest JupyterHub" setup on GCP cloud, the jupyterhub works fine, and as well the authentification with github. Then i would like to try the example dash board, however, it failed to build the dashboard with following error message.

![image](https://user-images.githubusercontent.com/18344140/83852812-a7864300-a714-11ea-8658-80ca15295371.png)

**Comment by Hanati** [comment]
closing the issue, forget to install `cdsdashboard` in the users environment, another problem, when providing the path for the dash code, give the relative path instead of the full path.

**Comment by danlester** [comment]
Thanks for the update! I'll see if I can improve the docs and error messages in the application to help with these scenarios.
