### ISSUE TITLE
Setting up different user groups with different default urls

### ISSUE THREAD

**Issue by tomnewg** [ideonate/cdsdashboards#20]
Hi all,

can we add to the section:
https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/finetune.html

A section on how to define different user groups and how to redirect them as you are likely to have technical and non-technical users and you want to differentiate their user experience.

Many thanks

Tom

**Comment by danlester** [comment]
@tomnewg I think this is a good idea - working out a good way to change the workflow for non-technical users.

Do you have tricks that have worked for you so far?

It might need some functionality in cdsdashboards to help with this, but a lot can probably be delegated to core JupyterHub functionality.

**Comment by danlester** [comment]
I have submitted a pull request to JupyterHub that will solve this problem:

https://github.com/jupyterhub/jupyterhub/pull/3133

**Comment by danlester** [comment]
This functionality is now available in jupyterhub master branch. Of course, ideally it will be in a full release soon enough.
