### ISSUE TITLE
Enhanced dashboard overview page

### ISSUE THREAD

**Issue by tomnewg** [ideonate/cdsdashboards#21]
It would be great for the user to create their own HTML overview for the individual dashboards in a similar fashion as the voila-gallery. Is there a place where I could store this HTML. I would then point the default URL to this HTML and the HTML has links to the individual dashboards

Many thanks

Tom

**Comment by tomnewg** [comment]
I actually found quite a neat and very easy way to do that. I created an additional notebook that contains HTML and links to individual dashboards. You then only have to create a new dashboard of this notebook and change the settings to load this dashboard when logging on to jupyterhub:

c.JupyterHub.default_url = '/user/<user name>/dash-<overview notebook>'

Let me know if anyone needs further explanation.

**Comment by danlester** [comment]
@tomnewg I love the idea - thanks for suggesting, and also for letting us know your solution!

If anyone else has a similar requirement that they don't feel is covered, please feel free to reopen this issue or just email me to discuss: dan@containds.com

**Comment by danlester** [comment]
I have submitted a pull request to the core JupyterHub project to cover this:

https://github.com/jupyterhub/jupyterhub/pull/3133

That is, the change allows you to provide a function that calculates different URLs depending on the user - e.g. /hub/home for admin users but a specific dashboard for everyone else.
