### ISSUE TITLE
Please add Panel to the set of supported frameworks

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ideonate/cdsdashboards#3]
Hi

I am a user of [Panel](https://panel.holoviz.org/) and a future user of JupyterHub. Please add support for Panel to your solution.

Panel is one of the four main python frameworks for building analytics apps and dashboards. Much more downloaded than for example Voila.

![image](https://user-images.githubusercontent.com/42288570/84264694-e86dc580-ab21-11ea-96c8-867b41a473ed.png)

If you want to see what kind of things can be developed in Panel checkout the video below or the site I develop awesome-panel.org.

![echarts](https://user-images.githubusercontent.com/42288570/84264503-9cbb1c00-ab21-11ea-9ef9-cc115dbece30.gif)

![detr_small](https://user-images.githubusercontent.com/42288570/84264477-8f9e2d00-ab21-11ea-9c99-17507ee83307.gif)

![perspective](https://user-images.githubusercontent.com/42288570/84264556-af355580-ab21-11ea-9905-6b913171dcb7.gif)

**Comment by danlester** [comment]
Thank you @philippjfr !

It should be mostly about tackling the usual reverse proxy issues, and then seeing how real-world Panel users get on trying it out.

I'll reach out with any questions.

**Comment by danlester** [comment]
OK there is support for 'bokeh' in the latest release 0.0.18, which also works with Panel of course.

BTW, the Voila option also works with Panel inside Jupyter notebooks, but probably best to use the native 'bokeh' option now.

It would be fantastic if bokeh/panel people can try it out!

User guide is [here](https://cdsdashboards.readthedocs.io/en/stable/chapters/userguide/bokehpanel.html).

Hopefully the basics should work, but I'll be really interested to hear how more advanced usage goes too.

Any specific issues can be reported on GitHub, or for more nuanced discussion please [email me](mailto:dan@containds.com).
