### ISSUE TITLE
Path with `'` refused

### ISSUE THREAD

**Issue by fcollonval** [ideonate/cdsdashboards#34]
**Describe the bug**

If the file used for the dashboard contains the character `'`, it won't work. In the form to create the dashboard, an error will appear telling the user the path is not a valid URL. And if the path in URL encoded, voila is not able to pick the notebook as the path it receives is encoded. Therefore voila is not finding the file.

**To Reproduce**

Name a notebook: `Bob's dashboard.ipynb`
Create a dashboard from that notebook, using the exact name you will the form will complain that the path is not a valid URL.
If `'` is replaced by `%27` in the form to create the dashboard, the dashboard form is valid. But voila will not spin the server due to a `FileNotFoundError`.

**Screenshots**
N/A

**Configuration**
LocalSpawner
voila

**Comment by danlester** [comment]
Thank you - I'll take a look

**Comment by danlester** [comment]
This has been fixed in https://github.com/ideonate/cdsdashboards/commit/f0059518b1a4645e37af9bc957a308edf3741b99
