### ISSUE TITLE
RShiny support?

### ISSUE THREAD

**Issue by elgalu** [ideonate/cdsdashboards#4]
Does cdsdashboards support [RShiny](https://github.com/rstudio/shiny) or did someone integrate them already? example?

**Comment by danlester** [comment]
Definitely on the list!

**Comment by danlester** [comment]
R Shiny Server is available in version 0.0.19 of cdsdashboards. Need to upgrade both hub and user environments of course.

Expects the path to a folder containing ui.R and server.R

For k8s, needs a 'singleuser' image containing all frameworks that you want. For the moment, the [prebuilt images](https://github.com/ideonate/cdsdashboards-jupyter-docker) either have RShiny and Voila, or all the non-RShiny frameworks. I'd like to build an image containing everything.

It would be great if RShiny enthusiasts could try it out!
