### ISSUE TITLE
Access Control?

### ISSUE THREAD

**Issue by elgalu** [ideonate/cdsdashboards#5]
Is it planned to support ACL? e.g. listing JupyerHub users that are allowed to open which dashboards.

**Comment by danlester** [comment]
Definitely important, and there is already a skeleton infrastructure based on JupyterHub Groups (which, in turn, don't have any UI...)

I am currently speaking to users to understand the higher-level use cases for Dashboards, and will go from there.

**Comment by elgalu** [comment]
SGTM, as long as one can allow specific users and/or specific groups, e.g.

```py
allowed_users = ["danlester", "elgalu"]
allowed_groups = ["mlops-team"]
```

**Comment by danlester** [comment]
For what it's worth, there is now a configuration option to default to only the dashboard creator having access, and then other users can be granted access by adding them to a specific JupyterHub Group:

See [Default User Access to Dashboards](https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/huboptions.html#default-user-access-to-dashboards)

However, JupyterHub doesn't have a UI for Groups, so permissions are still something that needs to be brought into ContainDS Dashboards in my opinion.

**Comment by elgalu** [comment]
I saw, IMHO this config should be per dashboard and flexible, i.e. by allowing to list specific allowed users and or allowed groups.

**Comment by danlester** [comment]
@elgalu Yes, definitely.

It needs a UI to at least toggle between 'all users' and 'selected users' per dashboard. And a UI to select which users in the latter case.

But I think for larger JupyterHubs the UI needs to be a bit more than basic in order to be workable. (e.g. a list of all users with checkboxes next to them would just be too big, so needs some JS to make it nice.)

The backend is there already at least!

**Comment by danlester** [comment]
This feature is [now available](https://cdsdashboards.readthedocs.io/en/stable/chapters/userguide/create_dashboard.html#user-permissions) in version 0.3.0! Thanks for the input everyone who made suggestions, especially @elgalu.
