### ISSUE TITLE
Make it easier to find the source code

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ideonate/cdsdashboards#6]
Hi

Whenever I want to find this repo I have to navigate to pypi https://pypi.org/project/cdsdashboards/ to find https://github.com/ideonate/cdsdashboards.

Please add GitHub link to

- readthedocs https://cdsdashboards.readthedocs.io/en/stable/
- homepage https://containds.com/

**Comment by danlester** [comment]
Great suggestion - thank you. This is just the kind of helpful thing that users are best positioned to notice.

**Comment by danlester** [comment]
There is now a [Source Code section](https://cdsdashboards.readthedocs.io/en/stable/chapters/sourcecode.html) on readthedocs

And the Dashboards menu on the [ContainDS website](https://containds.com/) contains links to GitHub and readthedocs.

Thanks again for pointing this out! I hope the improvements are helpful
