### ISSUE TITLE
Support Panel via panel serve

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ideonate/cdsdashboards#64]
I would like to be able to run Panel apps using ContainDS. I don't see that in the list of frameworks.

![image](https://user-images.githubusercontent.com/42288570/116296269-4dfa8d00-a79a-11eb-9c7a-f875619712e3.png)

Panel can no longer be started via `bokeh serve`. It needs to be started via `panel serve`. But everything else should be the same as Bokeh.

Thanks.

**Comment by MarcSkovMadsen** [comment]
Ok having looked at https://github.com/ideonate/bokeh-root-cmd/blob/master/bokeh_root_cmd/main.py I can see that you build the server your self instead of running it from the command line. My guess is that main purpose is to get the `ready-check`.

The will probably work for simple one file panel apps. And I can also see the most simple one working.

```python
import panel as pn
pn.extension()

pn.pane.Markdown("Hello World").servable()
```

I will close this one for now and return if I cannot serve more complicated Panel apps.

**Comment by danlester** [comment]
Thank you for this note - it's really useful to have your input from the cutting edge of Panel development!

Great if it still works for now, but please do let me know.

**Comment by congineer** [comment]
> Ok having looked at https://github.com/ideonate/bokeh-root-cmd/blob/master/bokeh_root_cmd/main.py I can see that you build the server your self instead of running it from the command line. My guess is that main purpose is to get the `ready-check`.
> 
> That will probably work for simple one file panel apps. And I can also see the most simple one working.
> 
> ```python
> import panel as pn
> pn.extension()
> 
> pn.pane.Markdown("Hello World").servable()
> ```
> 
> I will close this one for now and return if I cannot serve more complicated Panel apps.

Dear @MarcSkovMadsen and @danlester . Does anyone of you get Panel in TLJH cdsdashboards display any pane with more complex data than Markdown or HTML heading/paragraph?

I'm seeing any complex widget like Table Column with .servable() inside JupyterLab's panel extension button iframe, but not upon New Dashboard  as the cdsdashboards application window. The dashboard shows only trivial widgets with Markdown and HTML only ignoring all more complex widgets.

Is this a limitation of cdsdashboards?
