### ISSUE TITLE
Enable specifying resource limit on Kubernetes

### ISSUE THREAD

**Issue by MarcSkovMadsen** [ideonate/cdsdashboards#71]
My team will be using ContainDS to deploy on Kubernetes and our apps will have different resource requirements. Some will be very simple and some would be rather intense.

I would like the Dashboard creators to be able to specify the min and max limits for cpu and ram. Instead of just having a default size that is too much for most deployments and too little for a few.

**Comment by danlester** [comment]
Good point, potentially can be solved using profiles in KubeSpawner coupled with this option in ContainDS: https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/huboptions.html#spawner-user-options-form

Let me know your thoughts if you try it - have used it elsewhere though.
