### ISSUE TITLE
Batchspawner: Dashboard just shows Jupyter notebook

### ISSUE THREAD

**Issue by statiksof** [ideonate/cdsdashboards#82]
**Describe the bug**

I am using a customized spawner (options form) based on batchspawner but Dashboard just shows Jupyter server as normal as described [here](https://cdsdashboards.readthedocs.io/en/stable/chapters/troubleshooting.html#dashboard-just-shows-jupyter-server-as-normal).

Any additional configuration is required for batchspawner-based spawners?

**Configuration**

```
from batchspawner import SlurmSpawner
from cdsdashboards.hubextension.spawners.variablemixin import VariableMixin, MetaVariableMixin

class VariableSlurmSpawner(SlurmSpawner, VariableMixin, metaclass=MetaVariableMixin):
    pass

c.JupyterHub.spawner_class = VariableSlurmSpawner


c.VariableMixin.default_presentation_cmd = ['jhsingle-native-proxy']
```

**Comment by danlester** [comment]
Perhaps you've solved this by now, but the config looks right to me, so maybe the problem is down to your precise Slurm setup.

The only SlurmSpawner setup I've used personally is the [one here](https://github.com/Quansight/qhub-hpc/blob/main/templates/jupyterhub_config.py.j2) (there are a lot of extra bits and pieces, but the fundamentals are the same...) - not sure if that can give you any inspiration!

**Comment by statiksof** [comment]
Yes, I solved that issue (thank you for the link), our setup is a mix of profilesspawner and batchspawner (4 spawners in total), The problem was to find out who has to inherit from `VariableMixin and metaclass=MetaVariableMixin`. Now it works but sometimes it just stuck on building and nothing shows up:

```
DEBUG:tornado.application:Trying to start mainprocess
DEBUG:tornado.application:Started mainprocess
DEBUG:tornado.application:Connection to http://localhost:50342/ refused
DEBUG:tornado.application:Readyness: False after 0.011322975158691406 seconds, next check in 0.01s
DEBUG:tornado.application:Connection to http://localhost:50342/ refused
```
and in another cases, it starts after awhile, I believe there a networking configuration is required.

**Comment by jared-nussbaum-frbb** [comment]
Hi @statiksof . I think I am having the same issue as you had. Would you be able to share the code that resolved this issue for mixing ProfileSpawner and BatchSpawner while getting CDSDashboards to load? Or can you share what combination of `VariableMixin and metaclass=MetaVariableMixin` you found success with?
